### ISSUE TITLE
Cache retuns null address

### ISSUE THREAD

**Issue by mrengineer19** [Laralabs/get-address-io#5] opened 2020-12-16 08:51 UTC
Hi,

When the cache is enabled the result is null on 2nd request. Please see below API response.

Without Cache : https://www.screencast.com/t/h42w23t8CS

With cache (2nd request) : https://www.screencast.com/t/QC7RVvoVFdNp

**Comment by clnt** [comment] 2020-12-16 23:19
Hi @mrengineer19 - thanks for raising this, also good to know this has users!

Its been a long time since i've looked at the inner workings of this package, and I no longer use the getAddress API myself however I like to keep my packages maintained as best as possible so I will look into this issue as soon as I get the chance however I am very busy at the moment.

I will look at getting a free license key and do some testing to find the cause of the issue, however of course any PRs are welcome

**Comment by ahosker** [comment] 2021-05-25 17:35
You use something else instead @clnt ?

**Comment by clnt** [comment] 2021-07-28 18:13
Hi @mrengineer19 @ahosker 

Apologies for the slacking on getting this sorted!

I haven't used the service for a couple of years now but would like to keep this package up-to-date if it is being used.

Thanks to the PR #6 this should now be sorted so I am going to close this issue, if still encountering any issues feel free to open another.

Cheers,
Matt

**Closed as completed by clnt** 2021-07-28 18:13 UTC
